spring:    
  jackson:
    date-format: yyyy-MM-dd  
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

logging:
  file: target/app.log
  level:
    ROOT: WARN
    cn.devmgr: TRACE      